### PR TITLE
Basic backoff configuration for shard restarting

### PR DESCRIPTION
**Pull request by Yomanz**
Allows you to define a function that changes how shard restarts are determined.

Not sure why scalafmt went so mad

### CODE REVIEW

**Comment by Katrix** [comment]
Seems fine, but also think Scalafmt didn't pick up the configuration file. Can you fix the extra formatting?

**Comment by Yomanz** [comment]
oops

**Comment by Katrix** [comment]
Welp, nope, I'm just stupid, sorry. Seems I didn't push some stuff from when I updated Scalafmt

**Comment by Yomanz** [comment]
Do you want me to revert that reverted commit then?

**Comment by Yomanz** [comment]
Also I wasn't sure how to do it, but it would be cool if we could pass the amount of retries into the `restartBackoff` function so the end-user doesn't have to track it.

**Pull request merged**
